FROM restic/restic:0.18.1

USER root

RUN apk add --no-cache bash mariadb-client tzdata

COPY docker/backup.sh /usr/local/bin/wordpress-backup

RUN chmod 0755 /usr/local/bin/wordpress-backup

ENTRYPOINT ["/usr/local/bin/wordpress-backup"]
