docRoot                         $VH_ROOT/html/
vhDomain                        *
adminEmails                     root@localhost
enableGzip                      1

index {
    useServer                   0
    indexFiles                  index.php, index.html
    autoIndex                   0
}

context / {
    type                        null
    location                    $DOC_ROOT/
    allowBrowse                 1
    addDefaultCharset           off
}

rewrite {
    enable                      1
    autoLoadHtaccess            1
}

errorlog $VH_ROOT/logs/error.log {
    useServer                   1
}

accesslog $VH_ROOT/logs/access.log {
    useServer                   1
}

accessControl {
    deny
    allow                       *
}
